### ISSUE TITLE
ps3 wrong key bindings

### ISSUE THREAD

**Issue by torben** [hybridgroup/artoo-joystick#5]
Hi Codaz,

I've seen your :thumbsup: presentation at the rubyconf. Now I'm playing around with your Sphero and PS3-Joystick gems.

And with the ps3 I have a problem… My key binding is different to yours in the ps3.rb. When I'm observing the "triangle" key, I need to press the "select" key.

```
on joystick, :button_triangle => proc { |*value|
...
```

The "triangle" key is at my controller the "home" key.

I'm using ruby 2.0 and a mac on mavericks.

Do you have any idea where it comes from?

**Comment by torben** [comment]
This is my Binding:

```
BUTTON_MAP = {
        0 => 'select',
        1 => 'left_joystick',
        2 => 'right_joystick',
        3 => 'start',
        4 => 'up',
        5 => 'right',
        6 => 'down',
        7 => 'left',
        8 => 'l2',
        9 => 'r2',
        10 => 'l1',
        11 => 'r1',
        12 => 'triangle',
        13 => 'circle',
        14 => 'x',
        15 => 'square'
      }
```

**Comment by zankich** [comment]
@torben, yes this is a known issue that we're working on. In the meantime you can use the output from this example program to determine your button mapping 

https://github.com/hybridgroup/artoo-joystick/blob/master/examples/ps3_controller.rb#L11

and then make the appropriate changes in

https://github.com/hybridgroup/artoo-joystick/blob/master/lib/artoo/drivers/ps3.rb#L7

**Comment by juliancheal** [comment]
Fixed on commit https://github.com/hybridgroup/artoo-joystick/commit/c9f96fca63c5c51e1c98059d97ded24d7316a876
